development:
  store: timakasimov.myshopify.com
  theme_id: 132898160873
  password: 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
  
new-feature:
  store: timakasimov.myshopify.com
  theme_id: 132948361449
  password: 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
  
